server:
  port: 3344

spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lrh007/microservice-cloud-config.git   #github配置文件地址
          search-paths:
            - microservice-cloud-config #从这个路径下查询配置文件
          default-label: master    #默认读取master分支
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka