server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server

eureka:
  instance:
    hostname: eureka7001.com
    instance-id: cloud-eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false #不用注册到eureka中心
    fetch-registry: false #不从注册中心获取服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
#      defaultZone: http://localhost:7001/eureka/
