server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

feign:
  hystrix:
    enabled: true #feign 启用服务降级